### ISSUE TITLE
about code？

### ISSUE THREAD

**Issue by gjhhust** [HeQibin/TGraM#4]
Hello, you have done a very good job! May I ask whether your code can be disclosed now? I saw your work from your article and would like to learn it.Thank you very much for sharing!

**Comment by Wolfe233** [comment]
In another link have code

**Comment by gjhhust** [comment]
> In another link have code

I'm sorry, I can't find a similar link, can you send me the specific link

**Comment by Wolfe233** [comment]
> > In another link have code
> 
> I'm sorry, I can't find a similar link, can you send me the specific link

https://github.com/zuzi2015/TGraM

**Comment by gjhhust** [comment]
thanks！
